/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/cloud-ark/kubeplus-operators/moodle/pkg/apis/moodlecontroller/v1"
	scheme "github.com/cloud-ark/kubeplus-operators/moodle/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MoodlesGetter has a method to return a MoodleInterface.
// A group's client should implement this interface.
type MoodlesGetter interface {
	Moodles(namespace string) MoodleInterface
}

// MoodleInterface has methods to work with Moodle resources.
type MoodleInterface interface {
	Create(*v1.Moodle) (*v1.Moodle, error)
	Update(*v1.Moodle) (*v1.Moodle, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Moodle, error)
	List(opts metav1.ListOptions) (*v1.MoodleList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Moodle, err error)
	MoodleExpansion
}

// moodles implements MoodleInterface
type moodles struct {
	client rest.Interface
	ns     string
}

// newMoodles returns a Moodles
func newMoodles(c *MoodlecontrollerV1Client, namespace string) *moodles {
	return &moodles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the moodle, and returns the corresponding moodle object, and an error if there is any.
func (c *moodles) Get(name string, options metav1.GetOptions) (result *v1.Moodle, err error) {
	result = &v1.Moodle{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("moodles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Moodles that match those selectors.
func (c *moodles) List(opts metav1.ListOptions) (result *v1.MoodleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.MoodleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("moodles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested moodles.
func (c *moodles) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("moodles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a moodle and creates it.  Returns the server's representation of the moodle, and an error, if there is any.
func (c *moodles) Create(moodle *v1.Moodle) (result *v1.Moodle, err error) {
	result = &v1.Moodle{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("moodles").
		Body(moodle).
		Do().
		Into(result)
	return
}

// Update takes the representation of a moodle and updates it. Returns the server's representation of the moodle, and an error, if there is any.
func (c *moodles) Update(moodle *v1.Moodle) (result *v1.Moodle, err error) {
	result = &v1.Moodle{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("moodles").
		Name(moodle.Name).
		Body(moodle).
		Do().
		Into(result)
	return
}

// Delete takes name of the moodle and deletes it. Returns an error if one occurs.
func (c *moodles) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("moodles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *moodles) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("moodles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched moodle.
func (c *moodles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Moodle, err error) {
	result = &v1.Moodle{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("moodles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
